#EC2 Deployment
version: "3.9"

services:
  flask:
    image: ${ECR_REGISTRY}/${FLASK_REPO}:latest  #${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FLASK_APP}:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

  react:
    image: ${ECR_REGISTRY}/${REACT_REPO}:latest #${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REACT_APP}:latest
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Removed external: true
