#Build/Local
version: "3.9"

services:
  flask: #Service name used as arg by docker compose and build and also as proxy pass in nginx.conf
    #image: ${FLASK_APP}:latest
    image: react-app:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

    env_file: #Injects vars into the container
      - .env

    environment: #Overrides any env vars injected via .env
      FLASK_ENV: production

  react: #Service name used as arg by docker compose and build
    #image: ${REACT_APP}:latest
    image: flask-app:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


